name: CI

on:
  push:
    branches:
      - main
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache NPM
        uses: actions/cache@v3
        with:
          path: .cache/npm
          key: ${{ runner.os }}-npm-cache
      - name: Install dependencies
        run: npm install --quiet --no-progress --cache=.cache/npm
      - name: Bundle stable
        run: node_modules/.bin/gulp bundle
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ui-bundle
          path: build/ui-bundle.zip
      - name: Publish on S3
        run: node_modules/.bin/gulp uploadToS3 --awsAccessKeyId ${{ secrets.AWS_ACCESS_KEY_ID }} --awsSecretAccessKey ${{ secrets.AWS_SECRET_ACCESS_KEY }}

