name: CI

on:
  push:
    branches:
      - main
      - '**'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache NPM
        uses: actions/cache@v3
        with:
          path: .cache/npm
          key: ${{ runner.os }}-npm-cache
      - name: Install dependencies
        run: npm install --quiet --no-progress --cache=.cache/npm


  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.repository == 'berkhel/antora-ui-custom'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache NPM
        uses: actions/cache@v3
        with:
          path: .cache/npm
          key: ${{ runner.os }}-npm-cache
          restore-keys: |
            ${{ runner.os }}-npm-cache
      - name: Install dependencies
        run: npm install --quiet --no-progress --cache=.cache/npm
      - name: Bundle stable
        run: node_modules/.bin/gulp bundle
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ui-bundle
          path: build/ui-bundle.zip
